SUBROUTINE DFDXDOT(N, T, X, XDOT, Q, LROWQ, ML, MU, RPAR, LRP, IPAR, LIP)
    IMPLICIT NONE
    INTEGER :: N, LROWQ, ML, MU, LRP, LIP, IPAR(LIP)
    DOUBLE PRECISION :: T, X(N), XDOT(N), Q(LROWQ,N), RPAR(LRP)

END SUBROUTINE


