SUBROUTINE DFDX(N, T, X, XDOT, P, LROWP, ML, MU, RPAR, LRP, IPAR, LIP)
    IMPLICIT NONE
    INTEGER :: N, LROWP, ML, MU, LRP, LIP, IPAR(LIP)
    DOUBLE PRECISION :: T, X(N), XDOT(N), P(LROWP,N), RPAR(LRP)

END SUBROUTINE

